[repository]
name = "liquid-plastic-hyprpm"
authors = ["naddog1313"]

[liquid-plastic]
description = "High-gloss liquid plastic and refraction effects"
authors = ["naddog1313"]
output = "build/libliquid-plastic.so"
build = [
    "cmake -B build -DCMAKE_BUILD_TYPE=Release",
    "cmake --build build"
]

